version: "3.7"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    image: eperpus
    container_name: eperpus-web
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - eperpus-network

  db:
    image: mysql
    container_name: eperpus-db
    command: --authentication_policy=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - eperpus-network

  nginx:
    image: nginx:alpine
    container_name: eperpus-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - eperpus-network

networks:
  eperpus-network:
    driver: bridge
